name: "oj-resolve"
description: "A composite action that competitive-verifier oj-resolve"
author: "Kzrnm"
branding:
  color: blue
  icon: target
inputs:
  include:
    description: "Argument of oj-resolve --include."
    required: false
    default: ""
  exclude:
    description: "Argument of oj-resolve --exclude."
    required: false
    default: ""
  verify-files-path:
    description: "The file name of oj-resolve result json."
    required: false
    default: "./verify-files.json"
outputs:
  json-path:
    description: "The path of verify files json."
    value: ${{ steps.resolve.outputs.json-path }}
runs:
  using: composite
  steps:
    - name: oj-resolve
      shell: bash
      id: resolve
      run: |
        competitive-verifier oj-resolve --include $include --exclude $exclude > "$OUTPUT_FILE"
        cat "$OUTPUT_FILE"
        echo "json-path=$OUTPUT_FILE" >> $GITHUB_OUTPUT
      env:
        include: ${{ inputs.include }}
        exclude: ${{ inputs.exclude }}
        OUTPUT_FILE: ${{ inputs.verify-files-path }}
